### ISSUE TITLE
Improve connection config to make it support multi broker address ability (HA)

### ISSUE THREAD

**Issue by linustseng** [ppat/storm-rabbitmq#13]
We build a cluster of RabbitMQ and would like to apply its HA feature by modifying some code to meet requirement of rabbitmq java client. Just to replace argument from (host, port) to (address[]) and call different newConnection method by argument list. It will be great if the storm-rabbitmq component would support this feature as well.

Regards.

Please refer to the client API as below
http://www.rabbitmq.com/javadoc/com/rabbitmq/client/ConnectionFactory.html#newConnection(com.rabbitmq.client.Address[])

**Comment by drazzib** [comment]
Hi,

Support for multiple ```Adress[]``` in configuration seems to be handled since e5f8410e68e6df8e42b46c77073437c14195c3f8 commit (in 0.6.1 release)

I think we can close this issue.

**Comment by linustseng** [comment]
Great and sorry that I don't give anything on this issue. Thanks for your help.
