### ISSUE TITLE
About Trident

### ISSUE THREAD

**Issue by damacheng009** [ppat/storm-rabbitmq#14]
Can you support Trident spout?

**Comment by cloudbow** [comment]
Ppat, Can't we save the delivery tags in a list and then do an atomic operation of getting from the list and acking each individually?

**Comment by ppat** [comment]
I believe you need to ack an entire batch in atomic fashion. Not individually. Having said, if you have an implementation that works, pull requests are welcome (please follow the coding style within the project).
