### ISSUE TITLE
Support for activate and deactivate methods in RabbitMQSpout

### ISSUE THREAD

**Issue by arinto** [ppat/storm-rabbitmq#17]
The `io.latent.storm.rabbitmq.RabbitMQSpout` class doesn't override `BaseRichSpout` activate and deactivate methods. 

Here's my proposal
- `activate` method is following:
```
  @Override
  public void activate() {
    logger.info("activating spout!");
    consumer = loadConsumer(declarator, reporter, consConfig);
    scheme.open(topoConfig, topoContext);
    consumer.open();
    super.activate();
  }
 ```
We will cache `topoConfig` and `topoContext` from the `open` method.

- `deactivate` method is following:
``` 
 @Override
  public void deactivate() {
    logger.info("deactivating spout!");
    consumer.close();
    scheme.close();
    consumer = null;
    super.deactivate();
  }
```
I'll update this issue with my code in my development branch once it finishes

**Comment by ppat** [comment]
Closed by 0e438a383cd2187c66a94f933861a85663fd5eed
