### ISSUE TITLE
RabbitMQBolt always calls send(Message,"") without routing key

### ISSUE THREAD

**Issue by kandreadou** [ppat/storm-rabbitmq#29]
If I'm not mistaken, the RabbitMQBolt calls by default the producer method with an empty routing key producer.send(scheme.produceMessage(tuple)) even when using the variation of the constructor with the Declarator, which includes a routing key among other things. I find this a bit confusing. I would expect the send(Message, routingKey) method to be used when a Declarator is supplied. It might be a matter of personal taste though...

**Comment by ppat** [comment]
`Declarator` is for performing declarations and has nothing to do sending messages. Routing key to be used with message when sending messages are determined based on the implementation of `TupleToMessage` interface.
