### ISSUE TITLE
Maven central is missing version 0.6.1

### ISSUE THREAD

**Issue by heaje** [ppat/storm-rabbitmq#32]
It appears that the latest version of storm-rabbitmq in maven central is 0.6.0.  Any chance 0.6.1 could be put there?

**Comment by andreimaximov** [comment]
Same issue here

**Comment by drazzib** [comment]
Hi,

I'll work on this issue and publish an updated artifact on Maven Central.

**Comment by drazzib** [comment]
Hi @heaje and @andreimaximov !

I've just uploaded 0.6.1 release to Maven Central :
http://central.maven.org/maven2/io/latent/storm-rabbitmq/0.6.1/

Enjoy !
